### ISSUE TITLE
Azimuth and elevation issue

### ISSUE THREAD

**Issue by mjac-eag** [s-bear/sun-position#7]
Hi,

About a year ago I used your code for simulating PV prodution and it worked great. The accuracy of the azimuth and elevation angle was very helpful. Now I am trying to put together something similar again but I am facing some trouble with the azimuth and elevation angel.  As you can see in the picture the azimuth angle varies between 90 and 270 degrees where I believe it should vary between 0 to 360 degrees (or at least close to that), and the elevation angle should not only have a yearly pattern but also a daily, which it does not seem to have a the moment. 

If you have any ideas of what might be wrong I would sincerly appreciate the help. 
![sunposition_issue](https://github.com/s-bear/sun-position/assets/137042085/9467ad36-f731-44f6-95d4-ca64a1636ce7)

**Comment by s-bear** [comment]
I can't help with anything specific without seeing some example code.

With respect to the azimuth: An azimuth of 0 is to the north, increasing as you turn eastward, so 90 is east, 180 is south, and 270 is west, back to 360 again at north. If you're only looking at the azimuth when the sun is above the horizon, it will generally be southward in the northern hemisphere and northward in the southern hemisphere. In the tropics it will switch depending on the season. So observing azimuths only between 90 (East) and 270 (West) is expected for locations in the northern hemisphere during daylight hours.

With respect to your elevation angles... there certainly should be a daily change! Your issue might depend on your sampling rate? (E.g. if you sampled only daily at noon, it would show something similar to your plot)

I have a script around here somewhere for producing solar path diagrams, I'll upload it in a bit.

Cheers,
Sam

**Comment by mjac-eag** [comment]
Thanks for the reply, below is the code I wrote for creating the plot. 

Regards, 
Måns.
![sunposition_code](https://github.com/s-bear/sun-position/assets/137042085/0d7da218-bab8-48c3-990c-6be2620ff736)

**Comment by s-bear** [comment]
I see one immediate issue: `sunpos` and `observed_sunpos` return `(azimuth, zenith)`. The zenith angle is the angle from "up" down to the object, so `elevation = 90 - zenith`.

Otherwise, when I run your script (after renaming elevation to zenith), I get this:
![Figure_1](https://github.com/s-bear/sun-position/assets/4016348/7e751651-f807-4c70-ac76-19057d253b61)

It's possible that you're using out of date code--the first version I uploaded to pypi had a bug, though I don't remember exactly what it was. Try running `pip uninstall sunposition` and then `pip install sunposition`. The latest is version 1.1.1

**Comment by s-bear** [comment]
Also, here's my solar chart script, cleaned up a bit so it's not too embarassing: https://gist.github.com/s-bear/ce05cdb7883166d39914b081ee20cc4a

I never automated adding labels to the solar trace lines, so the charts are difficult to read, to say the least. The center of the chart is "up", the outside is the horizon. North is at the top, East on the right. The vertical-ish looped lines are hour-lines (E.g. the sun's position at 11 AM each day of the year), the horizontal lines are the sun's position over an entire day, from sunrise to sunset. The selected days are the solstices, equinoxes, and equally spaced days inbetween.

See https://www.autodesk.com/support/technical/article/caas/tsarticles/ts/2pGZ0xLAMCrBMy9xLtObJM.html for info on reading the chart (particularly useful since there aren't labels).

I've attached the chart produced by running it with the latitude and longitude you provided above:
`python .\solarchart.py -lat 50.482322 -lon 4.761905 -e 172 -y 2021`
![chart](https://github.com/s-bear/sun-position/assets/4016348/69688fad-da10-4242-8b02-69e0f0e4276f)

**Comment by mjac-eag** [comment]
Hi again, thanks a lot for the help. I managed to get it to work now.

**Comment by s-bear** [comment]
No worries & I'm glad to hear it! I've put the solarchart.py script in the dev branch (https://github.com/s-bear/sun-position/blob/dev/solarchart.py) with a few updates (labels, mostly), it might serve as an example on how to do some more complicated stuff with the library. Cheers, Sam
